name: hello-world

on:
  push:

jobs:
  build:
    runs-on: ubnuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Compile & Run
        run: make hello && ./hello

  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Compile & Run
        run: make hello && ./hello
