name: hello-world

on:
  push:

jobs:
  build1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Compile&Run
        run: make hello && ./hello

  build2:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Compile&Run
        run: make hello && ./hello
